# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'

        product.storage:
            adapter: 'aws'
            # visibility: public # Make the uploaded file publicly accessible in S3
            options:
                client: Aws\S3\S3Client
                bucket: '%env(BUCKETEER_BUCKET_NAME)%'
                prefix: 'products'
                streamReads: true

        category.storage:
            adapter: 'aws'
            # visibility: public # Make the uploaded file publicly accessible in S3
            options:
                client: Aws\S3\S3Client
                bucket: '%env(BUCKETEER_BUCKET_NAME)%'
                prefix: 'products'
                streamReads: true
