version: '3'

services:
  db-buddet:
    image: 'mysql/mysql-server:8.0'
    command:
      - "mysqld"
      - "--innodb_ft_min_token_size=1"
    ports:
      - '${FORWARD_DB_PORT:-3306}:${DB_PORT:-3306}'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_TCP_PORT: '${DB_PORT:-3306}'
    expose:
      - '${FORWARD_DB_PORT:-3306}'
    volumes:
      - 'db_buddet:/var/lib/mysql'
      - './mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - buddet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

volumes:
  db_buddet:

networks:
  buddet:
